/*
 * Projekt: Queen
 * Predmet: IJA - Seminar Java
 * Autori:
 *          xkolac12 < xkolac12 @ stud.fit.vutbr.cz >
 *          xmatya03 < xmatya03 @ stud.fit.vutbr.cz >
 */

package gui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 * @author      Frantisek Kolacek <xkolac12 @ stud.fit.vutbr.cz>
 * @version     0.91
 * @since       2013-04-30
 */
public class ReplayUI extends javax.swing.JFrame {

    private JMenuBar mainMenuBar;
    private JMenu mainMenuFile;
    private JMenuItem mainMenuFileLoad;
    private JMenuItem mainMenuFileQuit;
    private JMenu mainMenuHelp;
    private JMenuItem mainMenuHelpAbout;
    
    private Container content;

    public ReplayUI() {
        this.initWindow();
        this.initMenu();
        this.initContent();
        
        this.pack();
    }
    
    private void initWindow(){
        this.setTitle("Queen - Přehrávač partií");
        this.setIconImage(new ImageIcon(getClass().getResource("/gfx/icon.png")).getImage());

        this.setSize(600, 400);
        this.setResizable(false);
        this.setLocation(50, 50);
        
        this.setLocationRelativeTo(this);
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        this.setVisible(true);
    }
    
    private void initMenu(){
        //Create menu bar
        this.mainMenuBar = new JMenuBar();
        
        //Create each menu
        this.mainMenuFile = new JMenu("Soubor");
        this.mainMenuHelp = new JMenu("Nápověda");
        
        this.mainMenuFile.setMnemonic('S');
        this.mainMenuHelp.setMnemonic('N');
        
        //Create menu items
        this.mainMenuFileLoad = new JMenuItem("Načíst");
        this.mainMenuFileQuit = new JMenuItem("Ukončit");
        this.mainMenuHelpAbout = new JMenuItem("O programu");
        
        this.mainMenuFileLoad.setAccelerator(KeyStroke.getKeyStroke('O', KeyEvent.CTRL_DOWN_MASK));
        
        this.mainMenuFileLoad.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //handleDialogLoad(e);
            }
        });
        
        // Bind close event to Quit
        this.mainMenuFileQuit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
        
        this.mainMenuHelpAbout.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                handleDialogAbout(e);
            }
        });
        
        this.mainMenuFile.add(this.mainMenuFileLoad);
        this.mainMenuFile.add(new JSeparator());
        this.mainMenuFile.add(this.mainMenuFileQuit);
        this.mainMenuHelp.add(this.mainMenuHelpAbout);
        
        this.mainMenuBar.add(this.mainMenuFile);
        this.mainMenuBar.add(this.mainMenuHelp);
        
        this.setJMenuBar(this.mainMenuBar);        
    }
    
    private void initContent(){
        this.content = this.getContentPane();
        
        this.content.add(new BattleGroundUI());
    }
    
    private void handleDialogAbout(ActionEvent e){
        DialogAbout dialog = new DialogAbout(this, true);
        dialog.setLocationRelativeTo(this);
        
        dialog.setVisible(true);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReplayUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReplayUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReplayUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReplayUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReplayUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
