/*
 * Projekt: Queen
 * Predmet: IJA - Seminar Java
 * Soubor: DailogRawInput.java
 * Autori:
 *          xkolac12 < xkolac12 @ stud.fit.vutbr.cz >
 *          xmatya03 < xmatya03 @ stud.fit.vutbr.cz >
 * 
 * Trida DailogRawInput predstavuje dialog pro vlozeni postfix notace
 */

package gui;

import javax.swing.*;
import java.awt.*;
import javax.swing.JOptionPane;

/**
 * @author      Frantisek Kolacek <xkolac12 @ stud.fit.vutbr.cz>
 * @author      Petr Matyas <xmatya03 @ stud.fit.vutbr.cz>
 * @version     0.91
 * @since       2013-04-30
 */
public class DialogRawInput extends JDialog {

    private boolean accepted;
    
    /**
     * Vytvori objekt typu DialogRawInput
     */
    public DialogRawInput(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.accepted = false;
    }
    
    /**
     * Vraci vstupni text
     * @return vstupni text
     */
    public String getInputText(){
        return this.inputText.getText();
    }
    
    /**
     * Vraci, zda-li byl dialog potvrzen
     * @return true, pokud byl dialog potvrzen, jinak false
     */
    public boolean isAccepted(){
        return this.accepted;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inputText = new javax.swing.JTextArea();
        buttSubmit = new javax.swing.JButton();
        buttCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Qeen - Vstup notace");
        setResizable(false);

        inputText.setColumns(20);
        inputText.setRows(5);
        jScrollPane1.setViewportView(inputText);

        buttSubmit.setText("Vložit");
        buttSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttSubmitActionPerformed(evt);
            }
        });

        buttCancel.setText("Zrušit");
        buttCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttSubmit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttSubmit)
                    .addComponent(buttCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttCancelActionPerformed

    private void buttSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttSubmitActionPerformed
        if(this.inputText.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nelze načíst prázdnou hru!", "Queen - Chyba při načítání hry", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        this.accepted = true;
        this.dispose();
    }//GEN-LAST:event_buttSubmitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttCancel;
    private javax.swing.JButton buttSubmit;
    private javax.swing.JTextArea inputText;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
