/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;


import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JButton;






/**
 *
 * @author tuxik
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabPanel = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_pvp = new javax.swing.JMenuItem();
        menu_pvb = new javax.swing.JMenuItem();
        menu_pvw = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_net_make = new javax.swing.JMenuItem();
        menu_net_wait = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dáma");
        setMinimumSize(new java.awt.Dimension(845, 650));
        setPreferredSize(new java.awt.Dimension(845, 650));
        setResizable(false);

        TabPanel.setBackground(new java.awt.Color(153, 153, 255));

        jMenu1.setText("Nová hra");

        menu_pvp.setText("Hráč vs Hráč");
        menu_pvp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pvpActionPerformed(evt);
            }
        });
        jMenu1.add(menu_pvp);

        menu_pvb.setText("Hráč vs PC(černý)");
        menu_pvb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pvbActionPerformed(evt);
            }
        });
        jMenu1.add(menu_pvb);

        menu_pvw.setText("Hráč vs PC(bílý)");
        menu_pvw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pvwActionPerformed(evt);
            }
        });
        jMenu1.add(menu_pvw);
        jMenu1.add(jSeparator1);

        menu_net_make.setText("Vytvořit síťovou hru");
        menu_net_make.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_net_makeActionPerformed(evt);
            }
        });
        jMenu1.add(menu_net_make);

        menu_net_wait.setText("Očekávat síťovou hru");
        menu_net_wait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_net_waitActionPerformed(evt);
            }
        });
        jMenu1.add(menu_net_wait);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Načíst hru");

        jMenuItem1.setText("Lokální hra");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);
        jMenu2.add(jSeparator2);

        jMenuItem2.setText("Síťová hra");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Přehrát hru");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        menu_exit.setText("Konec");
        menu_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_exitMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_pvpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pvpActionPerformed
        try {        
            DeskWindow d = new DeskWindow(TabPanel);
            TabPanel.addTab("Hráč vs Hráč", null, d,"Hráč vs Hráč.");
            TabPanel.setSelectedComponent(d);
            d.Call_functions(0);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menu_pvpActionPerformed

    private void menu_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menu_exitMouseClicked

    private void menu_pvbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pvbActionPerformed
        try {    
            DeskWindow d = new DeskWindow(TabPanel);
            TabPanel.addTab("Hráč vs PC", null, d,"Hráč vs PC.");
            TabPanel.setSelectedComponent(d);
            d.Call_functions(1);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menu_pvbActionPerformed

    private void menu_pvwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pvwActionPerformed
        try {    
            DeskWindow d = new DeskWindow(TabPanel);
            TabPanel.addTab("PC vs Hráč", null, d,"PC vs Hráč.");
            TabPanel.setSelectedComponent(d);
            d.Call_functions(2);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menu_pvwActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {  
            DeskWindow d = new DeskWindow(TabPanel);
            TabPanel.addTab("Načtená hra", null, d,"Načtená hra");
            TabPanel.setSelectedComponent(d);
            d.Call_functions(3);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        try {  
            DeskWindow d = new DeskWindow(TabPanel);
            TabPanel.addTab("Přehrávání hry", null, d,"Přehrávání hry");
            TabPanel.setSelectedComponent(d);
            d.Call_functions(4);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu3MouseClicked

    private void menu_net_makeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_net_makeActionPerformed
        try {  
            DeskWindow d = new DeskWindow(TabPanel);
            TabPanel.addTab("Síťová hra", null, d,"Síťová hra");
            TabPanel.setSelectedComponent(d);
            d.Call_functions(5);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menu_net_makeActionPerformed

    private void menu_net_waitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_net_waitActionPerformed
        try {  
            DeskWindow d = new DeskWindow(TabPanel);
            TabPanel.addTab("Očekávání síťové hry", null, d,"očekávání síťové hry");
            TabPanel.setSelectedComponent(d);
            d.Call_functions(6);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menu_net_waitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu menu_exit;
    private javax.swing.JMenuItem menu_net_make;
    private javax.swing.JMenuItem menu_net_wait;
    private javax.swing.JMenuItem menu_pvb;
    private javax.swing.JMenuItem menu_pvp;
    private javax.swing.JMenuItem menu_pvw;
    // End of variables declaration//GEN-END:variables
}
